# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190129_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter')], max_length=25),
        ),
    ]
